name: 'woke'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  woke:
    name: 'woke'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Changed files'
        uses: jitterbit/get-changed-files@v1
        id: files
        continue-on-error: true

      - name: 'woke'
        uses: get-woke/woke-action@v0
        with:
          github-token: ${{ github.token }}
          # Cause the check to fail on any broke rules
          fail-on-error: true
          # See https://github.com/marketplace/actions/get-all-changed-files
          # for more options
          woke-args: ${{ steps.files.outputs.added_modified }}
